// Mocks generated by Mockito 5.1.0 from annotations
// in fordev/test/data/usecases/save_current_account/local_save_current_account_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:fordev/data/cache/save_secure_cache_storage.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [SaveSecureCacheStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveSecureCacheStorage extends _i1.Mock
    implements _i2.SaveSecureCacheStorage {
  MockSaveSecureCacheStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveSecure({String? key, String? value}) =>
      (super.noSuchMethod(
          Invocation.method(#saveSecure, [], {#key: key, #value: value}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
}
